apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
  namespace: default
  labels:
    app: flask-app
data:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  APP_PORT: "8080"
  APP_HOST: "0.0.0.0"
